name: CI
on:
  push:
    branches:
      - '**'

# TODO: Add test job

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test:unit
      - run: pnpm run build
